
security:
  oauth2:
    client:
      client-id: demouser
      client-secret: demopass
      user-authorization-uri: http://localhost:8080/oauth/authorize
      access-token-uri: http://localhost:8080/oauth/token
    resource:
      token-info-uri: http://localhost:8080/oauth/check_token
server:
  port: 7070
  servlet:
    session:
      cookie:
        name: KSESSION
